### ISSUE TITLE
Getting HTTPError in register_mozilla.html

### ISSUE THREAD

**Issue by cullub** [codedust/Textsecure-Browser#1]
![Screenshot](https://pageshot.net/images/591f72e5-edb1-4c5f-975c-d9c76ab9325b.png)

I'm getting this error quite consistently.  Any suggestions?  I can't rule anything out necessarily (including whether my HTTP server actually works...)

But I'd be happy to try anything!  I just don't exactly know where to start.

**Comment by cullub** [comment]
And no, that's not my phone number.  I tried it with my phone number.

**Comment by codedust** [comment]
Could you provide some more information from your browsers debug log (hit `F12`)? I guess the error might be related to the self-signed certificate of the development server.

**Comment by cullub** [comment]
Oh, yes.  I just tried going to the site manually and adding an exception for the security certificate, and that fixed it! Thanks.

PS: is there any way that we can make this not happen to new users (that you know of)?

**Comment by codedust** [comment]
Not having a signed certificate for the development server is an intended behaviour, as far as I know. Keep in mind that the mozilla branch is neither ready-to-use nor officially supported.
